### ISSUE TITLE
Usage example not working

### ISSUE THREAD

**Issue by lteyjolfur** [mtgatracker/python-mtga#22]
The usage example:
 from mtga.set_data import all_mtga_cards
print(all_mtga_cards.find_one("63773"))
results in:
ValueError("Pool does not contain {}".format(id_or_keyword))

Is this library deprecated?

**Comment by Spencatro** [comment]
This project has been around a long time; when it started, MTGA actually had the KLD cardset implemented. They removed it before launch though, since it had rotated, and since we use MTGA install files to dynamically load this module now, when you attempt to find a KLD card, it fails because it's not in MTGA anymore.

Fixed usage instructions in 0.9.5 to point to a card in M21. Thanks for pointing this out, and apologies that it took so dang long to fix!
